"""initial

Revision ID: e3a0322fb4ce
Revises:
Create Date: 2024-07-30 12:12:52.908156

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e3a0322fb4ce"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("create schema advertisement")
    op.execute("create schema classic")
    op.execute("create schema mass_selection_schema")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ad_call_center",
        sa.Column("stage_id", sa.String(length=512), nullable=True),
        sa.Column("source_id", sa.String(length=512), nullable=True),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_name", sa.String(length=512), nullable=True),
        sa.Column("UTM_term", sa.String(length=512), nullable=True),
        sa.Column("UTM_source", sa.String(length=512), nullable=True),
        sa.Column("UTM_medium", sa.String(length=512), nullable=True),
        sa.Column("UTM_content", sa.String(length=512), nullable=True),
        sa.Column("UTM_campaign", sa.String(length=512), nullable=True),
        sa.Column("lead_form", sa.Integer(), nullable=True),
        sa.Column("main_source", sa.String(length=512), nullable=True),
        sa.Column("secondary_source4", sa.String(length=512), nullable=True),
        sa.Column("secondary_source3", sa.String(length=512), nullable=True),
        sa.Column("secondary_source2", sa.String(length=512), nullable=True),
        sa.Column("secondary_source1", sa.String(length=512), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__ad_call_center")),
        sa.UniqueConstraint("id", name=op.f("uq__ad_call_center__id")),
        schema="advertisement",
    )
    op.create_index(
        op.f("ix__ad_call_center__deleted_at"),
        "ad_call_center",
        ["deleted_at"],
        unique=False,
        schema="advertisement",
    )
    op.create_table(
        "ad_mass_recruitment",
        sa.Column("stage_id", sa.String(length=512), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_name", sa.String(length=512), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__ad_mass_recruitment")),
        sa.UniqueConstraint("id", name=op.f("uq__ad_mass_recruitment__id")),
        schema="advertisement",
    )
    op.create_index(
        op.f("ix__ad_mass_recruitment__deleted_at"),
        "ad_mass_recruitment",
        ["deleted_at"],
        unique=False,
        schema="advertisement",
    )
    op.create_table(
        "ad_sng",
        sa.Column("stage_id", sa.String(length=512), nullable=True),
        sa.Column("source_id", sa.String(length=512), nullable=True),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=True),
        sa.Column("surname", sa.String(length=512), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__ad_sng")),
        sa.UniqueConstraint("id", name=op.f("uq__ad_sng__id")),
        schema="advertisement",
    )
    op.create_index(
        op.f("ix__ad_sng__deleted_at"),
        "ad_sng",
        ["deleted_at"],
        unique=False,
        schema="advertisement",
    )
    op.create_table(
        "ad_world",
        sa.Column("stage_id", sa.String(length=512), nullable=True),
        sa.Column("source_id", sa.String(length=512), nullable=True),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=True),
        sa.Column("surname", sa.String(length=512), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__ad_world")),
        sa.UniqueConstraint("id", name=op.f("uq__ad_world__id")),
        schema="advertisement",
    )
    op.create_index(
        op.f("ix__ad_world__deleted_at"),
        "ad_world",
        ["deleted_at"],
        unique=False,
        schema="advertisement",
    )
    op.create_table(
        "sng",
        sa.Column("assigned_by_id", sa.Integer(), nullable=True),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stage_id", sa.String(length=512), nullable=True),
        sa.Column("name", sa.String(length=512), nullable=True),
        sa.Column("last_name", sa.String(length=512), nullable=True),
        sa.Column("age", sa.String(length=512), nullable=True),
        sa.Column("birth_date", sa.String(length=512), nullable=True),
        sa.Column("passport", sa.Integer(), nullable=True),
        sa.Column("alabuga_start_game", sa.Integer(), nullable=True),
        sa.Column("refusal", sa.Integer(), nullable=True),
        sa.Column("sex", sa.Integer(), nullable=True),
        sa.Column("citizenship", sa.Integer(), nullable=True),
        sa.Column("date_of_unloading", sa.String(length=512), nullable=True),
        sa.Column("date_of_the_first_touch", sa.String(length=512), nullable=True),
        sa.Column("date_receipt_of_passport", sa.String(length=512), nullable=True),
        sa.Column("project", sa.String(length=512), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__sng")),
        sa.UniqueConstraint("id", name=op.f("uq__sng__id")),
        schema="classic",
    )
    op.create_index(
        op.f("ix__sng__deleted_at"),
        "sng",
        ["deleted_at"],
        unique=False,
        schema="classic",
    )
    op.create_table(
        "world",
        sa.Column("assigned_by_id", sa.Integer(), nullable=False),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_name", sa.String(length=512), nullable=False),
        sa.Column("last_name", sa.String(length=512), nullable=False),
        sa.Column("age", sa.String(length=512), nullable=True),
        sa.Column("gender", sa.Integer(), nullable=True),
        sa.Column("date_of_birth", sa.String(length=512), nullable=True),
        sa.Column("alabuga_start_simulation", sa.Integer(), nullable=False),
        sa.Column("rejection", sa.Integer(), nullable=True),
        sa.Column("citizenship_form", sa.Integer(), nullable=True),
        sa.Column("passport", sa.Integer(), nullable=False),
        sa.Column("passport_issue_date", sa.String(length=512), nullable=True),
        sa.Column("hundred_words", sa.Integer(), nullable=False),
        sa.Column("first_touch_date", sa.String(length=512), nullable=True),
        sa.Column("upload_date", sa.String(length=512), nullable=True),
        sa.Column("project", sa.Integer(), nullable=True),
        sa.Column("stage_id", sa.String(length=512), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__world")),
        sa.UniqueConstraint("id", name=op.f("uq__world__id")),
        schema="classic",
    )
    op.create_index(
        op.f("ix__world__deleted_at"),
        "world",
        ["deleted_at"],
        unique=False,
        schema="classic",
    )
    op.create_table(
        "mass_selection",
        sa.Column("stage", sa.String(length=512), nullable=True),
        sa.Column("assessment_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("solution", sa.Integer(), nullable=True),
        sa.Column("user_name", sa.String(length=512), nullable=True),
        sa.Column("comments", sa.Integer(), nullable=True),
        sa.Column("sp", sa.Integer(), nullable=True),
        sa.Column("body_check", sa.Integer(), nullable=True),
        sa.Column("age", sa.Float(), nullable=True),
        sa.Column("employment_stage", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__mass_selection")),
        sa.UniqueConstraint("id", name=op.f("uq__mass_selection__id")),
        schema="mass_selection_schema",
    )
    op.create_index(
        op.f("ix__mass_selection__deleted_at"),
        "mass_selection",
        ["deleted_at"],
        unique=False,
        schema="mass_selection_schema",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix__mass_selection__deleted_at"),
        table_name="mass_selection",
        schema="mass_selection_schema",
    )
    op.drop_table("mass_selection", schema="mass_selection_schema")
    op.drop_index(op.f("ix__world__deleted_at"), table_name="world", schema="classic")
    op.drop_table("world", schema="classic")
    op.drop_index(op.f("ix__sng__deleted_at"), table_name="sng", schema="classic")
    op.drop_table("sng", schema="classic")
    op.drop_index(
        op.f("ix__ad_world__deleted_at"), table_name="ad_world", schema="advertisement"
    )
    op.drop_table("ad_world", schema="advertisement")
    op.drop_index(
        op.f("ix__ad_sng__deleted_at"), table_name="ad_sng", schema="advertisement"
    )
    op.drop_table("ad_sng", schema="advertisement")
    op.drop_index(
        op.f("ix__ad_mass_recruitment__deleted_at"),
        table_name="ad_mass_recruitment",
        schema="advertisement",
    )
    op.drop_table("ad_mass_recruitment", schema="advertisement")
    op.drop_index(
        op.f("ix__ad_call_center__deleted_at"),
        table_name="ad_call_center",
        schema="advertisement",
    )
    op.drop_table("ad_call_center", schema="advertisement")
    # ### end Alembic commands ###
