services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: $APP_DATABASE_USER
      POSTGRES_PASSWORD: $APP_DATABASE_PASSWORD
      POSTGRES_DB: $APP_DATABASE_NAME
    ports:
      - $APP_DATABASE_PORT:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  worker:
    build: .
    restart: unless-stopped
    environment:
      APP_DATABASE_HOST: db
      APP_DATABASE_PORT: 5432
      APP_DATABASE_USER: $APP_DATABASE_USER
      APP_DATABASE_PASSWORD: $APP_DATABASE_PASSWORD
      APP_DATABASE_NAME: $APP_DATABASE_NAME

      APP_BITRIX_WEBHOOK: $APP_BITRIX_WEBHOOK
      APP_BITRIX_SNG_ENTITY_ID: $APP_BITRIX_SNG_ENTITY_ID
      APP_BITRIX_WORLD_ENTITY_ID: $APP_BITRIX_WORLD_ENTITY_ID
      APP_BITRIX_CHUNK_SIZE: $APP_BITRIX_CHUNK_SIZE
      APP_BITRIX_CALL_CENTER_ENTITY_ID: $APP_BITRIX_CALL_CENTER_ENTITY_ID
      APP_BITRIX_MASS_RECRUITMENT_ENTITY_ID: $APP_BITRIX_MASS_RECRUITMENT_ENTITY_ID

      APP_DEBUG: $APP_DEBUG
      APP_SCHEDULER_CRON_SPEC: $APP_SCHEDULER_CRON_SPEC

      APP_LOG_LEVEL: $APP_LOG_LEVEL
      APP_LOG_FORMAT: $APP_LOG_FORMAT

    depends_on:
      - db


volumes:
  postgres_data: