version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-webserver:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__RBAC: 'True'
    ports:
      - "8080:8080"
    volumes:
      - ./airflow:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./models:/opt/airflow/models
    command: webserver

  airflow-scheduler:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ./airflow:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./models:/opt/airflow/models
    command: scheduler

volumes:
  postgres_data: